/**
 * Catálogo padrão de itens de manutenção preventiva e receitas potenciais da oficina (Story 2.13 / AC2).
 * Fixo em código nesta release.
 */

export const ITENS_PREVENTIVOS_CATALOGO = [
  {
    id: 'oleo_filtros',
    nome: 'Troca de Óleo e Filtros',
    categoria: 'Lubrificação',
    descricao: 'Óleo sintético ou semissintético, filtro de óleo, ar do motor e combustível',
    intervaloKmPadrao: 10000,
    intervaloMesesPadrao: 6,
    valorEstimadoMedio: 350.0,
    tempoEstimadoMinutos: 45,
    severidade: 'alta',
    icone: 'Drop',
  },
  {
    id: 'pastilhas_freio',
    nome: 'Pastilhas e Discos de Freio',
    categoria: 'Segurança e Freios',
    descricao: 'Inspeção de espessura de pastilhas dianteiras/traseiras, discos e sangria',
    intervaloKmPadrao: 20000,
    intervaloMesesPadrao: 12,
    valorEstimadoMedio: 420.0,
    tempoEstimadoMinutos: 60,
    severidade: 'alta',
    icone: 'Gauge',
  },
  {
    id: 'fluido_arrefecimento',
    nome: 'Fluido de Arrefecimento e Radiador',
    categoria: 'Arrefecimento',
    descricao: 'Limpeza química do sistema, aditivo orgânico concentrado e teste de estanqueidade',
    intervaloKmPadrao: 30000,
    intervaloMesesPadrao: 24,
    valorEstimadoMedio: 280.0,
    tempoEstimadoMinutos: 50,
    severidade: 'alta',
    icone: 'ThermometerHot',
  },
  {
    id: 'palhetas_limpador',
    nome: 'Troca de Palhetas do Limpador',
    categoria: 'Visibilidade e Conforto',
    descricao: 'Substituição das palhetas do para-brisa dianteiro e traseiro por silicone',
    intervaloKmPadrao: 10000,
    intervaloMesesPadrao: 6,
    valorEstimadoMedio: 120.0,
    tempoEstimadoMinutos: 15,
    severidade: 'baixa',
    icone: 'Wind',
  },
  {
    id: 'revisao_basica',
    nome: 'Revisão Básica Periódica',
    categoria: 'Revisão Periódica',
    descricao: 'Checklist de 30 itens, suspensão leve, freios, iluminação e calibração',
    intervaloKmPadrao: 10000,
    intervaloMesesPadrao: 6,
    valorEstimadoMedio: 480.0,
    tempoEstimadoMinutos: 90,
    severidade: 'media',
    icone: 'ShieldCheck',
  },
  {
    id: 'revisao_pesada_correia',
    nome: 'Revisão Pesada e Correia Dentada',
    categoria: 'Motor e Transmissão',
    descricao: 'Kit correia sincronizadora, tensionadores, bomba d água e velas de ignição',
    intervaloKmPadrao: 50000,
    intervaloMesesPadrao: 36,
    valorEstimadoMedio: 1650.0,
    tempoEstimadoMinutos: 240,
    severidade: 'alta',
    icone: 'Wrench',
  },
  {
    id: 'fluido_freio',
    nome: 'Fluido de Freio DOT 4 ou 5.1',
    categoria: 'Segurança e Freios',
    descricao: 'Teste de umidade/ebulição e sangria completa com máquina pressurizada',
    intervaloKmPadrao: 20000,
    intervaloMesesPadrao: 24,
    valorEstimadoMedio: 190.0,
    tempoEstimadoMinutos: 45,
    severidade: 'alta',
    icone: 'Gauge',
  },
  {
    id: 'alinhamento_balanceamento',
    nome: 'Alinhamento 3D e Balanceamento',
    categoria: 'Suspensão e Direção',
    descricao: 'Alinhamento a laser 3D, balanceamento das 4 rodas e rodízio de pneus',
    intervaloKmPadrao: 10000,
    intervaloMesesPadrao: 6,
    valorEstimadoMedio: 160.0,
    tempoEstimadoMinutos: 45,
    severidade: 'media',
    icone: 'Compass',
  },
  {
    id: 'ar_condicionado_cabine',
    nome: 'Higienização de Ar e Filtro Cabine',
    categoria: 'Climatização e Saúde',
    descricao: 'Aplicação de ozônio bactericida e troca do filtro de pólen antipoeira',
    intervaloKmPadrao: 10000,
    intervaloMesesPadrao: 6,
    valorEstimadoMedio: 180.0,
    tempoEstimadoMinutos: 30,
    severidade: 'baixa',
    icone: 'Fan',
  },
  {
    id: 'fluido_cambio',
    nome: 'Fluido de Câmbio Automático ou CVT',
    categoria: 'Motor e Transmissão',
    descricao: 'Troca por diálise com fluido sintético certificado e filtro de cárter',
    intervaloKmPadrao: 40000,
    intervaloMesesPadrao: 36,
    valorEstimadoMedio: 1100.0,
    tempoEstimadoMinutos: 120,
    severidade: 'alta',
    icone: 'GearSix',
  },
  {
    id: 'bateria_carga',
    nome: 'Bateria e Sistema Elétrico',
    categoria: 'Elétrica',
    descricao: 'Teste de condutância e CCA, carga do alternador e terminais de polo',
    intervaloKmPadrao: 30000,
    intervaloMesesPadrao: 24,
    valorEstimadoMedio: 490.0,
    tempoEstimadoMinutos: 25,
    severidade: 'media',
    icone: 'Lightning',
  },
  {
    id: 'revisao_garantia',
    nome: 'Revisão de Retorno e Garantia',
    categoria: 'Garantia de Serviços',
    descricao: 'Inspeção periódica obrigatória para revalidação de garantia da oficina',
    intervaloKmPadrao: 5000,
    intervaloMesesPadrao: 3,
    valorEstimadoMedio: 0.0,
    tempoEstimadoMinutos: 30,
    severidade: 'alta',
    icone: 'SealCheck',
  },
]
