// Constantes de Servicos de Terceiros, Parceiros Fornecedores e Categorias
// Regra: Sem uso do caractere proibido (apenas a conjuncao 'e')

export const PARCEIROS_TERCEIROS = [
  {
    id: 'parc-1',
    nome: 'Retífica Bandeirantes',
    razaoSocial: 'Retífica Bandeirantes de Motores e Cabeçotes Ltda',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3214-5500',
    whatsapp: '11991234567',
    especialidade: 'Retífica de Cabeçotes, Bloco, Virabrequim e Bielas',
    tempoMedioEntrega: '1 a 2 dias úteis',
    avaliacao: 4.9,
    ativo: true,
  },
  {
    id: 'parc-2',
    nome: 'Tornearia e Soldas Precision',
    razaoSocial: 'Precision Usinagem e Soldas Industriais Eireli',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3322-8811',
    whatsapp: '11982345678',
    especialidade: 'Usinagem em Torno, Solda TIG e MIG, Extração de Prisioneiros',
    tempoMedioEntrega: 'Mesmo dia útil (4 a 6 horas)',
    avaliacao: 4.8,
    ativo: true,
  },
  {
    id: 'parc-3',
    nome: 'Laboratório Eletrônico TechCar',
    razaoSocial: 'TechCar Reparos e Diagnósticos Eletrônicos Automotivos',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3455-9922',
    whatsapp: '11973456789',
    especialidade: 'Reparo e Desbloqueio de Módulos ECU, Painéis, ABS e Airbag',
    tempoMedioEntrega: '2 a 3 dias úteis',
    avaliacao: 4.9,
    ativo: true,
  },
  {
    id: 'parc-4',
    nome: 'Rei dos Radiadores e Arrefecimento',
    razaoSocial: 'Rei dos Radiadores e Serviços Térmicos Ltda',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3566-7733',
    whatsapp: '11964567890',
    especialidade: 'Varetagem, Teste Hidrostático e Solda de Colmeias',
    tempoMedioEntrega: '4 a 8 horas',
    avaliacao: 4.7,
    ativo: true,
  },
  {
    id: 'parc-5',
    nome: 'Hidráulica Brasil Caixas de Direção',
    razaoSocial: 'Brasil Caixas e Bombas de Direção Hidráulica',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3677-4455',
    whatsapp: '11955678901',
    especialidade: 'Recondicionamento de Caixas Mecânicas, Hidráulicas e Elétricas',
    tempoMedioEntrega: '1 a 2 dias úteis',
    avaliacao: 4.8,
    ativo: true,
  },
  {
    id: 'parc-6',
    nome: 'Guincho e Reboque 24h Express',
    razaoSocial: 'Express Resgate e Guincho Plataforma Ltda',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3788-1122',
    whatsapp: '11946789012',
    especialidade: 'Transporte de Veículos e Reboque Leve e Médio',
    tempoMedioEntrega: '45 minutos (Imediato)',
    avaliacao: 4.9,
    ativo: true,
  },
]

export const CATEGORIAS_TERCEIROS_OPCOES = [
  { value: 'Retífica de Motor e Cabeçote', label: 'Retífica de Motor e Cabeçote' },
  { value: 'Tornearia e Usinagem', label: 'Tornearia e Usinagem' },
  { value: 'Módulos e Eletrônica', label: 'Módulos e Eletrônica' },
  { value: 'Soldas Especiais', label: 'Soldas Especiais' },
  { value: 'Direção Hidráulica e Elétrica', label: 'Direção Hidráulica e Elétrica' },
  { value: 'Radiadores e Arrefecimento', label: 'Radiadores e Arrefecimento' },
  { value: 'Injeção Diesel e Bicos', label: 'Injeção Diesel e Bicos' },
  { value: 'Guincho e Transporte', label: 'Guincho e Transporte' },
  { value: 'Funilaria e Pintura', label: 'Funilaria e Pintura' },
  { value: 'Outros Especializados', label: 'Outros Especializados' },
]

export const STATUS_TERCEIRO_OPCOES = [
  { value: 'aguardando_envio', label: 'Aguardando Envio' },
  { value: 'para_cotacao', label: 'Para Cotação' },
  { value: 'em_execucao', label: 'Em Execução Externa' },
  { value: 'pronto_para_retirada', label: 'Pronto para Retirada' },
  { value: 'concluido', label: 'Concluído e Instalado' },
  { value: 'cancelado', label: 'Cancelado' },
]

export const PRAZO_TERCEIRO_OPCOES = [
  { value: 'Mesmo dia útil (4 a 6 horas)', label: 'Mesmo dia útil (4 a 6 horas)' },
  { value: '1 dia útil (24 horas)', label: '1 dia útil (24 horas)' },
  { value: '2 dias úteis', label: '2 dias úteis' },
  { value: '3 a 5 dias úteis', label: '3 a 5 dias úteis' },
  { value: 'A combinar', label: 'A combinar' },
]

export const CATALOGO_SERVICOS_TERCEIROS = [
  {
    codigo: 'TER-001',
    nome: 'Retífica e Plaina de Cabeçote de Alumínio',
    categoria: 'Retífica de Motor e Cabeçote',
    custoPadrao: 280.0,
    valorVendaPadrao: 420.0,
    parceiroPadraoId: 'parc-1',
    parceiroPadraoNome: 'Retífica Bandeirantes',
    prazoPadrao: '1 dia útil (24 horas)',
    garantiaPadrao: '6 meses',
    descricao: 'Teste hidrostático de trinca, plaina da face de vedação e assentamento de válvulas.',
  },
  {
    codigo: 'TER-002',
    nome: 'Teste Hidrostático de Cabeçote (Verificação de Trinca)',
    categoria: 'Retífica de Motor e Cabeçote',
    custoPadrao: 150.0,
    valorVendaPadrao: 240.0,
    parceiroPadraoId: 'parc-1',
    parceiroPadraoNome: 'Retífica Bandeirantes',
    prazoPadrao: 'Mesmo dia útil (4 a 6 horas)',
    garantiaPadrao: 'Garantia de laudo',
    descricao: 'Banho quente pressurizado para detecção de microfissuras internas nas galerias de água.',
  },
  {
    codigo: 'TER-003',
    nome: 'Usinagem e Torneamento de Volante do Motor',
    categoria: 'Tornearia e Usinagem',
    custoPadrao: 90.0,
    valorVendaPadrao: 160.0,
    parceiroPadraoId: 'parc-2',
    parceiroPadraoNome: 'Tornearia e Soldas Precision',
    prazoPadrao: 'Mesmo dia útil (4 a 6 horas)',
    garantiaPadrao: '3 meses',
    descricao: 'Torneamento da face de atrito para perfeito acoplamento do disco de embreagem sem trepidação.',
  },
  {
    codigo: 'TER-004',
    nome: 'Extração de Prisioneiro Quebrado em Bloco ou Cubo',
    categoria: 'Tornearia e Usinagem',
    custoPadrao: 120.0,
    valorVendaPadrao: 200.0,
    parceiroPadraoId: 'parc-2',
    parceiroPadraoNome: 'Tornearia e Soldas Precision',
    prazoPadrao: 'Mesmo dia útil (4 a 6 horas)',
    garantiaPadrao: '3 meses',
    descricao: 'Remoção técnica com usinagem sem danificar a rosca original da carcaça.',
  },
  {
    codigo: 'TER-005',
    nome: 'Solda TIG Especial em Cárter de Alumínio',
    categoria: 'Soldas Especiais',
    custoPadrao: 180.0,
    valorVendaPadrao: 290.0,
    parceiroPadraoId: 'parc-2',
    parceiroPadraoNome: 'Tornearia e Soldas Precision',
    prazoPadrao: 'Mesmo dia útil (4 a 6 horas)',
    garantiaPadrao: '6 meses',
    descricao: 'Soldagem em atmosfera inerte para fechamento de trincas ou recuperação de rosca do bujão.',
  },
  {
    codigo: 'TER-006',
    nome: 'Reparo e Desbloqueio de Módulo de Injeção Eletrônica (ECU)',
    categoria: 'Módulos e Eletrônica',
    custoPadrao: 550.0,
    valorVendaPadrao: 890.0,
    parceiroPadraoId: 'parc-3',
    parceiroPadraoNome: 'Laboratório Eletrônico TechCar',
    prazoPadrao: '2 dias úteis',
    garantiaPadrao: '6 meses',
    descricao: 'Substituição de drivers de bobina, bicos injetores e reprogramação de mapa original.',
  },
  {
    codigo: 'TER-007',
    nome: 'Reparo e Teste de Bancada em Módulo ABS',
    categoria: 'Módulos e Eletrônica',
    custoPadrao: 420.0,
    valorVendaPadrao: 680.0,
    parceiroPadraoId: 'parc-3',
    parceiroPadraoNome: 'Laboratório Eletrônico TechCar',
    prazoPadrao: '2 dias úteis',
    garantiaPadrao: '6 meses',
    descricao: 'Recondicionamento da placa eletrônica e motor elétrico da bomba de ABS.',
  },
  {
    codigo: 'TER-008',
    nome: 'Recondicionamento de Caixa de Direção Hidráulica',
    categoria: 'Direção Hidráulica e Elétrica',
    custoPadrao: 480.0,
    valorVendaPadrao: 790.0,
    parceiroPadraoId: 'parc-5',
    parceiroPadraoNome: 'Hidráulica Brasil Caixas de Direção',
    prazoPadrao: '1 a 2 dias úteis',
    garantiaPadrao: '6 meses',
    descricao: 'Troca de retentores, anéis de vedação teflon e brunimento do eixo cremalheira.',
  },
  {
    codigo: 'TER-009',
    nome: 'Varetagem e Solda em Radiador de Arrefecimento',
    categoria: 'Radiadores e Arrefecimento',
    custoPadrao: 160.0,
    valorVendaPadrao: 260.0,
    parceiroPadraoId: 'parc-4',
    parceiroPadraoNome: 'Rei dos Radiadores e Arrefecimento',
    prazoPadrao: 'Mesmo dia útil (4 a 6 horas)',
    garantiaPadrao: '3 meses',
    descricao: 'Desobstrução interna de galerias de arrefecimento e teste de pressão com banho de estanqueidade.',
  },
  {
    codigo: 'TER-010',
    nome: 'Transporte de Veículo em Guincho Plataforma',
    categoria: 'Guincho e Transporte',
    custoPadrao: 150.0,
    valorVendaPadrao: 220.0,
    parceiroPadraoId: 'parc-6',
    parceiroPadraoNome: 'Guincho e Reboque 24h Express',
    prazoPadrao: 'Mesmo dia útil (4 a 6 horas)',
    garantiaPadrao: 'Seguro de Carga Incluso',
    descricao: 'Resgate seguro do veículo até a oficina com operador credenciado.',
  },
]
