export const SISTEMAS = [
  { value: "motor", label: "Motor", subsistemas: ["Bloco do motor", "Arrefecimento interno", "Sistema de oleo", "Correias e tensor", "Comando de valvulas", "Turbo"] },
  { value: "lubrificacao", label: "Lubrificacao", subsistemas: ["Carter", "Filtro de oleo", "Tampa de enchimento", "Radiador de oleo"] },
  { value: "arrefecimento", label: "Arrefecimento", subsistemas: ["Radiador", "Reservatorio de expansao", "Bomba dagua", "Termostatica", "Ventoinha", "Mangueiras", "Junta de cabecote"] },
  { value: "alimentacao", label: "Alimentacao de Combustivel", subsistemas: ["Tanque", "Bomba de combustivel", "Filtro de combustivel", "Regulador de pressao", "Bicos injetores", "Corpo de borboleta"] },
  { value: "admissao", label: "Admissao e Ignicao", subsistemas: ["Filtro de ar", "Coletor de admissao", "Velas de ignicao", "Bobinas de ignicao"] },
  { value: "eletronica", label: "Gerenciamento Eletronico", subsistemas: ["ECU/ECM", "Sensores", "Atuadores", "Chicote eletrico", "Modulo de injecao", "Rede CAN"] },
  { value: "escapamento", label: "Escapamento e Emissoes", subsistemas: ["Coletor de escape", "Catalisador", "Silenciador", "Sensor lambda", "EGR", "FAP/DPF"] },
  { value: "turbo", label: "Turboalimentacao", subsistemas: ["Corpo do turbo", "Atuador de pressao", "Intercooler", "Mangueiras de boost"] },
  { value: "embreagem", label: "Embreagem", subsistemas: ["Disco de embreagem", "Plato", "Rolete guia", "Cilindro mestre", "Cilindro escravo"] },
  { value: "transmissao_manual", label: "Transmissao Manual", subsistemas: ["Caixa de cambio", "Syncromesh", "Alavanca de cambio", "Mancais", "Rolamentos"] },
  { value: "transmissao_auto", label: "Transmissao Automatica", subsistemas: ["Conversor de torque", "Painel de valvulas", "Freios e bandas", "Embreagens internas", "Oleo ATF"] },
  { value: "transmissao_cvt", label: "Transmissao CVT", subsistemas: ["Polias", "Corrente/Correia", "Conversor de torque", "Oleo CVT"] },
  { value: "semi_eixo", label: "Semieixos e Diferencial", subsistemas: ["Semieixos", "Homocineticas", "Diferencial dianteiro", "Diferencial traseiro", "Caixa de transferencia"] },
  { value: "freios", label: "Freios", subsistemas: ["Disco de freio", "Pastilha de freio", "Tambor de freio", "Sapata de freio", "Cilindro de roda", "Fluido de freio"] },
  { value: "abs", label: "ABS, Tracao e Estabilidade", subsistemas: ["Modulo ABS", "Sensor de roda", "Anel encoder", "Atuador hidraulico"] },
  { value: "direcao", label: "Direcao", subsistemas: ["Caixa de direcao", "Coluna de direcao", "Barra de direcao", "Extremidades", "Liquido hidraulico", "Bomba de direcao"] },
  { value: "suspensao", label: "Suspensao", subsistemas: ["Amortecedor", "Mola", "Bieleta", "Terminal de direcao", "Apoio de suspensao", "Junta homocinetica", "Braco de suspensao", "Estabilizador"] },
  { value: "pneus", label: "Pneus e Rodas", subsistemas: ["Pneu dianteiro", "Pneu traseiro", "Roda", "Calibragem", "Alinhamento", "Balanceamento"] },
  { value: "eletrica", label: "Sistema Eletrico", subsistemas: ["Chicote geral", "Fusiveis", "Reles", "Aterramento", "Fiacao", "Conectores"] },
  { value: "partida_carga", label: "Partida e Carga", subsistemas: ["Motor de partida", "Alternador", "Bateria", "Bornes e cabos", "Regulador de tensao"] },
  { value: "iluminacao", label: "Iluminacao e Sinalizacao", subsistemas: ["Farol principal", "Farol de neblina", "Luz de re", "Seta", "Luz de freio", "Painel de instrumentos"] },
  { value: "ar_condicionado", label: "Ar-Condicionado", subsistemas: ["Compressor", "Condensador", "Evaporador", "Tubulacao", "Gas refrigerante", "Filtro de cabine"] },
  { value: "carroceria", label: "Carroceria", subsistemas: ["Portas", "Capo", "Teto", "Porta-malas", "Para-choques"] },
  { value: "interior", label: "Interior e Conforto", subsistemas: ["Bancos", "Painel", "Forro", "Carpetes", "Vidros eletricos", "Travas eletricas"] },
  { value: "airbag", label: "Airbag e Seguranca", subsistemas: ["Modulo de airbag", "Airbag do motorista", "Airbag do passageiro", "Cortinas", "Pre-tensores", "Cintos"] },
  { value: "comunicacao", label: "Rede de Comunicacao", subsistemas: ["Rede CAN", "Rede LIN", "Modulo de comunicacao", "Gateway", "Scanner OBD-II"] },
  { value: "hibrido_eletrico", label: "Veiculo Hibrido ou Eletrico", subsistemas: ["Bateria de tracao", "Motor eletrico", "Inversor", "Carregador"] },
  { value: "outro_sistema", label: "Outro", subsistemas: ["Especificar"] },
]

export const SINTOMAS = [
  { value: "ruido_pancada", label: "Ruido de pancada" },
  { value: "estalo", label: "Estalo" },
  { value: "rangido", label: "Rangido" },
  { value: "vibracao", label: "Vibracao" },
  { value: "perda_potencia", label: "Perda de potencia" },
  { value: "vazamento", label: "Vazamento" },
  { value: "dificuldade_partida", label: "Dificuldade de partida" },
  { value: "luz_acesa", label: "Luz de advertencia acesa" },
  { value: "superaquecimento", label: "Superaquecimento" },
  { value: "consumo_elevado", label: "Consumo elevado" },
  { value: "veiculo_puxa", label: "Veiculo puxando para um lado" },
  { value: "falha_funcionamento", label: "Falha de funcionamento" },
  { value: "motor_dorme", label: "Motor morre em marcha lenta" },
  { value: "fumaca", label: "Emissao de fumaca" },
  { value: "cheiro", label: "Cheiro anormal" },
  { value: "tranco", label: "Tranco na troca de marcha" },
  { value: "desalinhamento_volante", label: "Desalinhamento de volante" },
  { value: "folga_direcao", label: "Folga na direcao" },
  { value: "pedal_firme", label: "Pedal excessivamente firme" },
  { value: "pedal_fofo", label: "Pedal fofa ou no chao" },
  { value: "nao_entra_marcha", label: "Nao entra em marcha" },
  { value: "ruido_freio", label: "Ruido ao frear" },
  { value: "pulsacao_freio", label: "Pulsacao no pedal de freio" },
  { value: "desgaste_pneu", label: "Desgaste irregular de pneus" },
  { value: "ar_nao_gela", label: "Ar-condicionado nao gela" },
  { value: "barulho_ar", label: "Barulho no ar-condicionado" },
  { value: "vidro_nao_funciona", label: "Vidro nao funciona" },
  { value: "trava_nao_funciona", label: "Trava nao funciona" },
  { value: "retrovisor_nao_funciona", label: "Retrovisor nao funciona" },
  { value: "buzina_nao_toca", label: "Buzina nao toca" },
  { value: "farol_fraco", label: "Farol com pouca luminosidade" },
  { value: "scanner_erro", label: "Codigo de falha no scanner" },
  { value: "outro_sintoma", label: "Outro sintoma" },
]

export const CONDICOES = [
  { value: "ausente", label: "Ausente" },
  { value: "abaixo_nivel", label: "Abaixo do nivel" },
  { value: "acima_nivel", label: "Acima do nivel" },
  { value: "aberto", label: "Aberto" },
  { value: "desalinhado", label: "Desalinhado" },
  { value: "desbalanceado", label: "Desbalanceado" },
  { value: "descalibrado", label: "Descalibrado" },
  { value: "desconectado", label: "Desconectado" },
  { value: "desgastado", label: "Desgastado" },
  { value: "deformado", label: "Deformado" },
  { value: "deteriorado", label: "Deteriorado" },
  { value: "danificado", label: "Danificado" },
  { value: "empenado", label: "Empenado" },
  { value: "folga", label: "Folga" },
  { value: "folga_excessiva", label: "Folga excessiva" },
  { value: "incompativel", label: "Incompativel" },
  { value: "inoperante", label: "Inoperante" },
  { value: "intermitente", label: "Intermitente" },
  { value: "invertido", label: "Invertido" },
  { value: "obstruido", label: "Obstruido" },
  { value: "oxidado", label: "Oxidado" },
  { value: "quebrado", label: "Quebrado" },
  { value: "ressecado", label: "Ressecado" },
  { value: "rompido", label: "Rompido" },
  { value: "ruidoso", label: "Ruidoso" },
  { value: "saturado", label: "Saturado" },
  { value: "sem_alimentacao", label: "Sem alimentacao" },
  { value: "sem_comunicacao", label: "Sem comunicacao" },
  { value: "sem_pressao", label: "Sem pressao" },
  { value: "solto", label: "Solto" },
  { value: "sujo", label: "Sujo" },
  { value: "superaquecido", label: "Superaquecido" },
  { value: "travado_aberto", label: "Travado aberto" },
  { value: "travado_fechado", label: "Travado fechado" },
  { value: "vazando", label: "Vazando" },
  { value: "vibrando", label: "Vibrando" },
  { value: "fora_especificacao", label: "Fora da especificacao" },
  { value: "nao_avaliado", label: "Nao foi possivel avaliar" },
  { value: "outra_condicao", label: "Outra condicao" },
]

export const POSICOES = [
  { value: "dianteira", label: "Dianteira" },
  { value: "traseira", label: "Traseira" },
  { value: "central", label: "Central" },
  { value: "dianteira_esquerda", label: "Dianteira esquerda" },
  { value: "dianteira_direita", label: "Dianteira direita" },
  { value: "traseira_esquerda", label: "Traseira esquerda" },
  { value: "traseira_direita", label: "Traseira direita" },
  { value: "lado_esquerdo", label: "Lado esquerdo" },
  { value: "lado_direito", label: "Lado direito" },
  { value: "superior", label: "Superior" },
  { value: "inferior", label: "Inferior" },
  { value: "interna", label: "Interna" },
  { value: "externa", label: "Externa" },
  { value: "banco_1", label: "Banco 1" },
  { value: "banco_2", label: "Banco 2" },
  { value: "cilindro", label: "Cilindro especifico" },
  { value: "geral", label: "Geral" },
  { value: "nao_definida", label: "Nao definida" },
  { value: "nao_se_aplica", label: "Nao se aplica" },
]

export const CONDICOES_SINTOMA = [
  { value: "motor_frio", label: "Motor frio" },
  { value: "motor_quente", label: "Motor quente" },
  { value: "marcha_lenta", label: "Em marcha lenta" },
  { value: "aceleracao", label: "Durante aceleracao" },
  { value: "frenagem", label: "Durante frenagem" },
  { value: "curvas", label: "Em curvas" },
  { value: "piso_irregular", label: "Em piso irregular" },
  { value: "velocidade_especifica", label: "Em determinada velocidade" },
  { value: "subida", label: "Em subida" },
  { value: "descida", label: "Em descida" },
  { value: "intermitente", label: "De forma intermitente" },
  { value: "sempre", label: "Ocorre sempre" },
  { value: "outra_condicao", label: "Outra condicao" },
]

export const METODOS_VERIFICACAO = [
  { value: "inspecao_visual", label: "Inspecao visual" },
  { value: "inspecao_tatil", label: "Inspecao tatil" },
  { value: "verificacao_folga", label: "Verificacao manual de folga" },
  { value: "teste_rodagem", label: "Teste de rodagem" },
  { value: "scanner", label: "Scanner automotivo" },
  { value: "multimetro", label: "Multimetro" },
  { value: "osciloscopio", label: "Osciloscopio" },
  { value: "manometro", label: "Manometro" },
  { value: "teste_compressao", label: "Teste de compressao" },
  { value: "teste_estanqueidade", label: "Teste de estanqueidade" },
  { value: "teste_pressao", label: "Teste de pressao" },
  { value: "teste_vazao", label: "Teste de vazao" },
  { value: "teste_bateria", label: "Teste de bateria" },
  { value: "teste_carga", label: "Teste do sistema de carga" },
  { value: "teste_fumaca", label: "Teste de fumaca" },
  { value: "analise_gases", label: "Analise de gases" },
  { value: "desmontagem_parcial", label: "Desmontagem parcial" },
  { value: "comparacao_especificacao", label: "Comparacao com especificacao tecnica" },
  { value: "outro_metodo", label: "Outro metodo" },
]

export const STATUS_DIAGNOSTICO = [
  { value: "nao_avaliado", label: "Nao avaliado", color: "bg-[#f2f4f7] text-[#667085] border-[#d0d5dd]" },
  { value: "em_teste", label: "Em teste", color: "bg-[#f0f9ff] text-[#026aa2] border-[#b9e6fe]" },
  { value: "sintoma_nao_reproduzido", label: "Sintoma nao reproduzido", color: "bg-[#f8fafc] text-[#344054] border-[#d0d5dd]" },
  { value: "inconclusivo", label: "Inconclusivo", color: "bg-[#fffaeb] text-[#b54708] border-[#fedf89]" },
  { value: "suspeita", label: "Suspeita", color: "bg-[#fff4e6] text-[#93370d] border-[#f4c89a]" },
  { value: "causa_provavel", label: "Causa provavel", color: "bg-[#fef3f2] text-[#b42318] border-[#fecdca]" },
  { value: "diagnostico_confirmado", label: "Diagnostico confirmado", color: "bg-[#ecfdf3] text-[#027a48] border-[#a6f4c5]" },
  { value: "falha_nao_encontrada", label: "Falha nao encontrada", color: "bg-[#f2f4f7] text-[#344054] border-[#d0d5dd]" },
  { value: "avaliacao_nao_autorizada", label: "Avaliacao nao autorizada", color: "bg-[#fef3f2] text-[#b42318] border-[#fecdca]" },
]

export const STATUS_QUEIXA = [
  { value: "nao_avaliada", label: "Nao avaliada", color: "bg-[#f2f4f7] text-[#667085] border-[#d0d5dd]" },
  { value: "em_diagnostico", label: "Em diagnostico", color: "bg-[#f0f9ff] text-[#026aa2] border-[#b9e6fe]" },
  { value: "sintoma_nao_reproduzido", label: "Sintoma nao reproduzido", color: "bg-[#f8fafc] text-[#344054] border-[#d0d5dd]" },
  { value: "causa_provavel", label: "Causa provavel", color: "bg-[#fffaeb] text-[#b54708] border-[#fedf89]" },
  { value: "diagnostico_confirmado", label: "Diagnostico confirmado", color: "bg-[#ecfdf3] text-[#027a48] border-[#a6f4c5]" },
  { value: "concluida", label: "Concluida", color: "bg-[#ecfdf3] text-[#027a48] border-[#a6f4c5]" },
]

export const PRIORIDADE_REPARO = [
  { value: "informativa", label: "Informativa", color: "bg-[#f8fafc] text-[#344054] border-[#d0d5dd]" },
  { value: "baixa", label: "Baixa", color: "bg-[#f0f9ff] text-[#026aa2] border-[#b9e6fe]" },
  { value: "media", label: "Media", color: "bg-[#fffaeb] text-[#b54708] border-[#fedf89]" },
  { value: "alta", label: "Alta", color: "bg-[#fef3f2] text-[#b42318] border-[#fecdca]" },
  { value: "critica", label: "Critica", color: "bg-[#b42318] text-white border-[#b42318]" },
]

export const IMPACTO_FALHA = [
  { value: "conforto", label: "Conforto" },
  { value: "funcionamento", label: "Funcionamento" },
  { value: "desempenho", label: "Desempenho" },
  { value: "confiabilidade", label: "Confiabilidade" },
  { value: "consumo", label: "Consumo" },
  { value: "emissoes", label: "Emissoes" },
  { value: "seguranca", label: "Seguranca" },
  { value: "dano_progressivo", label: "Possibilidade de dano progressivo" },
  { value: "imobilizacao", label: "Imobilizacao do veiculo" },
]

export const LIBERACAO_VEICULO = [
  { value: "normal", label: "Veiculo pode ser utilizado normalmente" },
  { value: "curto_prazo", label: "Recomenda-se reparo em curto prazo" },
  { value: "evitar_prolongada", label: "Recomenda-se evitar utilizacao prolongada" },
  { value: "nova_avaliacao", label: "Necessita nova avaliacao antes da liberacao" },
  { value: "nao_liberar", label: "Nao recomendar utilizacao ate a correcao" },
]

export const ORIGEM_APONTAMENTO = [
  { value: "queixa_cliente", label: "Queixa do cliente" },
  { value: "revisao_preventiva", label: "Revisao preventiva" },
  { value: "inspecao", label: "Item encontrado durante inspecao" },
  { value: "problema_adicional", label: "Problema adicional" },
  { value: "nao_relacionado", label: "Nao relacionado a uma queixa" },
]

export const STATUS_MEDICAO = [
  { value: "conforme", label: "Conforme" },
  { value: "abaixo_especificacao", label: "Abaixo da especificacao" },
  { value: "acima_especificacao", label: "Acima da especificacao" },
  { value: "inconclusivo", label: "Inconclusivo" },
]

export const STATUS_DTC = [
  { value: "presente", label: "Presente" },
  { value: "intermitente", label: "Intermitente" },
  { value: "historico", label: "Historico" },
  { value: "pendente", label: "Pendente" },
  { value: "permanente", label: "Permanente" },
]
