// Constantes de Auto Pecas Fornecedoras, Catalogo com Estoque e Categorias de Pecas
// Regra: Sem uso do caractere proibido (apenas 'e')

export const AUTO_PECAS_FORNECEDORES = [
  {
    id: 'forn-1',
    nome: 'Auto Peças Central',
    razaoSocial: 'Central Distribuidora de Auto Peças Ltda',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3456-7890',
    whatsapp: '11987654321',
    especialidade: 'Freios, Suspensão e Direção',
    tempoMedioEntrega: '1 a 2 horas (Rápido)',
    avaliacao: 4.9,
    ativo: true,
  },
  {
    id: 'forn-2',
    nome: 'Distribuidora União Autopeças',
    razaoSocial: 'União Comércio de Peças e Componentes',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3567-8901',
    whatsapp: '11976543210',
    especialidade: 'Motor, Arrefecimento e Transmissão',
    tempoMedioEntrega: '2 a 3 horas',
    avaliacao: 4.8,
    ativo: true,
  },
  {
    id: 'forn-3',
    nome: 'Rei das Peças Express',
    razaoSocial: 'Rei Auto Peças e Baterias Eireli',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3678-9012',
    whatsapp: '11998871122',
    especialidade: 'Elétrica, Injeção Eletrônica e Baterias',
    tempoMedioEntrega: '45 minutos (Moto Express)',
    avaliacao: 4.7,
    ativo: true,
  },
  {
    id: 'forn-4',
    nome: 'Renova Peças Automotivas',
    razaoSocial: 'Renova Distribuição de Peças e Filtros',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3789-0123',
    whatsapp: '11981112233',
    especialidade: 'Filtros, Lubrificantes e Acessórios',
    tempoMedioEntrega: '1 hora',
    avaliacao: 4.9,
    ativo: true,
  },
  {
    id: 'forn-5',
    nome: 'Distribuidora Nacional de Peças',
    razaoSocial: 'Nacional Peças e Latarias Automotivas',
    cidade: 'São Paulo - SP',
    telefone: '(11) 3890-1234',
    whatsapp: '11972223344',
    especialidade: 'Lataria, Faróis, Pneus e Suspensão Pesada',
    tempoMedioEntrega: 'Mesmo dia útil',
    avaliacao: 4.8,
    ativo: true,
  },
]

export const CATEGORIAS_PECAS_OPCOES = [
  { value: 'Freios', label: 'Freios' },
  { value: 'Suspensão', label: 'Suspensão' },
  { value: 'Motor', label: 'Motor' },
  { value: 'Lubrificantes e Filtros', label: 'Lubrificantes e Filtros' },
  { value: 'Arrefecimento', label: 'Arrefecimento' },
  { value: 'Elétrica e Ignição', label: 'Elétrica e Ignição' },
  { value: 'Transmissão', label: 'Transmissão' },
  { value: 'Direção', label: 'Direção' },
  { value: 'Ar Condicionado', label: 'Ar Condicionado' },
  { value: 'Escapamento', label: 'Escapamento' },
  { value: 'Pneus e Rodas', label: 'Pneus e Rodas' },
  { value: 'Outros Componentes', label: 'Outros Componentes' },
]

export const CATEGORIAS_PECAS = CATEGORIAS_PECAS_OPCOES.map((c) => c.value)

export const CATALOGO_PECAS_ESTOQUE = [
  {
    codigo: 'PEC-001',
    nome: 'Pastilhas de Freio Dianteiras',
    categoria: 'Freios',
    precoUnitario: 180.0,
    estoqueAtual: 4,
    estoqueMinimo: 2,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-1',
    fornecedorNome: 'Auto Peças Central',
    marcaSugerida: 'Fras-le / Bosch',
  },
  {
    codigo: 'PEC-002',
    nome: 'Discos de Freio Ventilados Dianteiros (Par)',
    categoria: 'Freios',
    precoUnitario: 320.0,
    estoqueAtual: 0,
    estoqueMinimo: 1,
    statusEstoque: 'para_cotacao',
    fornecedorId: 'forn-1',
    fornecedorNome: 'Auto Peças Central',
    marcaSugerida: 'Fremax / Hipper Freios',
  },
  {
    codigo: 'PEC-003',
    nome: 'Amortecedores Dianteiros (Par)',
    categoria: 'Suspensão',
    precoUnitario: 580.0,
    estoqueAtual: 0,
    estoqueMinimo: 1,
    statusEstoque: 'para_cotacao',
    fornecedorId: 'forn-1',
    fornecedorNome: 'Auto Peças Central',
    marcaSugerida: 'Cofap / Monroe',
  },
  {
    codigo: 'PEC-004',
    nome: 'Kit Batentes e Coifas dos Amortecedores',
    categoria: 'Suspensão',
    precoUnitario: 120.0,
    estoqueAtual: 2,
    estoqueMinimo: 1,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-1',
    fornecedorNome: 'Auto Peças Central',
    marcaSugerida: 'Sampel / Axios',
  },
  {
    codigo: 'PEC-005',
    nome: 'Bieletas da Barra Estabilizadora (Par)',
    categoria: 'Suspensão',
    precoUnitario: 95.0,
    estoqueAtual: 3,
    estoqueMinimo: 2,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-1',
    fornecedorNome: 'Auto Peças Central',
    marcaSugerida: 'Nakata / Viemar',
  },
  {
    codigo: 'PEC-006',
    nome: 'Óleo de Motor Sintético 5W30 (Litro)',
    categoria: 'Lubrificantes e Filtros',
    precoUnitario: 48.0,
    estoqueAtual: 24,
    estoqueMinimo: 8,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-4',
    fornecedorNome: 'Renova Peças Automotivas',
    marcaSugerida: 'Mobil / Castrol / Motul',
  },
  {
    codigo: 'PEC-007',
    nome: 'Filtro de Óleo do Motor',
    categoria: 'Lubrificantes e Filtros',
    precoUnitario: 38.0,
    estoqueAtual: 8,
    estoqueMinimo: 4,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-4',
    fornecedorNome: 'Renova Peças Automotivas',
    marcaSugerida: 'Tecfil / Mann Filter',
  },
  {
    codigo: 'PEC-008',
    nome: 'Filtro de Ar do Motor',
    categoria: 'Lubrificantes e Filtros',
    precoUnitario: 45.0,
    estoqueAtual: 6,
    estoqueMinimo: 2,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-4',
    fornecedorNome: 'Renova Peças Automotivas',
    marcaSugerida: 'Tecfil / Fram',
  },
  {
    codigo: 'PEC-009',
    nome: 'Filtro de Cabine (Ar Condicionado)',
    categoria: 'Lubrificantes e Filtros',
    precoUnitario: 42.0,
    estoqueAtual: 5,
    estoqueMinimo: 2,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-4',
    fornecedorNome: 'Renova Peças Automotivas',
    marcaSugerida: 'Tecfil / Mann',
  },
  {
    codigo: 'PEC-010',
    nome: 'Filtro de Combustível',
    categoria: 'Lubrificantes e Filtros',
    precoUnitario: 35.0,
    estoqueAtual: 7,
    estoqueMinimo: 3,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-4',
    fornecedorNome: 'Renova Peças Automotivas',
    marcaSugerida: 'Tecfil / Mahle',
  },
  {
    codigo: 'PEC-011',
    nome: 'Correia Dentada de Sincronismo e Tensor',
    categoria: 'Motor',
    precoUnitario: 280.0,
    estoqueAtual: 0,
    estoqueMinimo: 1,
    statusEstoque: 'para_cotacao',
    fornecedorId: 'forn-2',
    fornecedorNome: 'Distribuidora União Autopeças',
    marcaSugerida: 'Gates / Continental',
  },
  {
    codigo: 'PEC-012',
    nome: 'Bomba d Água do Arrefecimento',
    categoria: 'Arrefecimento',
    precoUnitario: 210.0,
    estoqueAtual: 0,
    estoqueMinimo: 1,
    statusEstoque: 'para_cotacao',
    fornecedorId: 'forn-2',
    fornecedorNome: 'Distribuidora União Autopeças',
    marcaSugerida: 'Urba / Schadek',
  },
  {
    codigo: 'PEC-013',
    nome: 'Válvula Termostática com Carcaça',
    categoria: 'Arrefecimento',
    precoUnitario: 165.0,
    estoqueAtual: 0,
    estoqueMinimo: 1,
    statusEstoque: 'para_cotacao',
    fornecedorId: 'forn-2',
    fornecedorNome: 'Distribuidora União Autopeças',
    marcaSugerida: 'Wahler / MTE-Thomson',
  },
  {
    codigo: 'PEC-014',
    nome: 'Líquido de Arrefecimento Aditivo Orgânico (Litro)',
    categoria: 'Arrefecimento',
    precoUnitario: 36.0,
    estoqueAtual: 14,
    estoqueMinimo: 6,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-4',
    fornecedorNome: 'Renova Peças Automotivas',
    marcaSugerida: 'Paraflu / Koube',
  },
  {
    codigo: 'PEC-015',
    nome: 'Velas de Ignição (Jogo 4 unidades)',
    categoria: 'Elétrica e Ignição',
    precoUnitario: 140.0,
    estoqueAtual: 4,
    estoqueMinimo: 2,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-3',
    fornecedorNome: 'Rei das Peças Express',
    marcaSugerida: 'NGK / Bosch',
  },
  {
    codigo: 'PEC-016',
    nome: 'Cabos de Vela de Ignição',
    categoria: 'Elétrica e Ignição',
    precoUnitario: 130.0,
    estoqueAtual: 2,
    estoqueMinimo: 1,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-3',
    fornecedorNome: 'Rei das Peças Express',
    marcaSugerida: 'NGK / Delphi',
  },
  {
    codigo: 'PEC-017',
    nome: 'Bobina de Ignição',
    categoria: 'Elétrica e Ignição',
    precoUnitario: 260.0,
    estoqueAtual: 0,
    estoqueMinimo: 1,
    statusEstoque: 'para_cotacao',
    fornecedorId: 'forn-3',
    fornecedorNome: 'Rei das Peças Express',
    marcaSugerida: 'Bosch / Delphi / Magneti Marelli',
  },
  {
    codigo: 'PEC-018',
    nome: 'Bateria Automotiva 60Ah Selada',
    categoria: 'Elétrica e Ignição',
    precoUnitario: 430.0,
    estoqueAtual: 3,
    estoqueMinimo: 1,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-3',
    fornecedorNome: 'Rei das Peças Express',
    marcaSugerida: 'Moura / Heliar',
  },
  {
    codigo: 'PEC-019',
    nome: 'Kit de Embreagem (Platô, Disco e Rolamento)',
    categoria: 'Transmissão',
    precoUnitario: 620.0,
    estoqueAtual: 0,
    estoqueMinimo: 1,
    statusEstoque: 'para_cotacao',
    fornecedorId: 'forn-2',
    fornecedorNome: 'Distribuidora União Autopeças',
    marcaSugerida: 'LUK / Sachs / Valeo',
  },
  {
    codigo: 'PEC-020',
    nome: 'Pivôs de Suspensão Dianteira (Par)',
    categoria: 'Suspensão',
    precoUnitario: 150.0,
    estoqueAtual: 2,
    estoqueMinimo: 1,
    statusEstoque: 'em_estoque',
    fornecedorId: 'forn-1',
    fornecedorNome: 'Auto Peças Central',
    marcaSugerida: 'Nakata / TRW',
  },
]
