export const MENU_CATEGORIES = [
  {
    id: 'operacoes',
    title: 'Operações',
    items: [
      {
        id: 'resumo',
        label: 'Resumo',
        path: '/gestao/dashboard',
        icon: 'SquaresFour',
        description: 'Visão geral de indicadores, faturamento, atendimentos e alertas da oficina.',
      },
      {
        id: 'agenda',
        label: 'Agenda',
        path: '/gestao/agenda',
        icon: 'CalendarDots',
        description: 'Agendamentos de revisões, entregas de veículos e controle de boxes.',
      },
      {
        id: 'ordem-de-servico',
        label: 'Ordem de Serviço',
        path: '/gestao/ordem-de-servico',
        icon: 'ClipboardText',
        description: 'Emissão, aprovação de orçamentos e acompanhamento de OSs em andamento.',
      },
      {
        id: 'pdv',
        label: 'PDV',
        path: '/gestao/pdv',
        icon: 'CreditCard',
        description: 'Frente de caixa para vendas rápidas de peças, produtos e recebimentos.',
      },
    ],
  },
  {
    id: 'clientes-patio',
    title: 'Atendimento & Pátio',
    items: [
      {
        id: 'clientes',
        label: 'Clientes',
        path: '/gestao/clientes',
        icon: 'Users',
        description: 'Cadastro completo de pessoas físicas e jurídicas, contatos e histórico.',
      },
      {
        id: 'veiculos',
        label: 'Veículos',
        path: '/gestao/veiculos',
        icon: 'CarProfile',
        description: 'Ficha técnica de veículos, histórico de manutenção, placas e quilometragens.',
      },
      {
        id: 'estacionados',
        label: 'Estacionados',
        path: '/gestao/estacionados',
        icon: 'Garage',
        description: 'Controle de vagas, pátio interno e veículos aguardando peças ou liberação.',
      },
      {
        id: 'leva-e-traz',
        label: 'Leva e Traz',
        path: '/gestao/leva-e-traz',
        icon: 'ArrowsLeftRight',
        description: 'Gestão de coletas, entregas a domicílio e rotas de motoristas da oficina.',
      },
    ],
  },
  {
    id: 'oficina',
    title: 'Oficina Técnica',
    items: [
      {
        id: 'manutencao-preventiva',
        label: 'Manutenção Preventiva',
        path: '/gestao/manutencao-preventiva',
        icon: 'ShieldCheck',
        description: 'Planos de revisão por quilometragem, tempo e alertas automáticos aos clientes.',
      },
      {
        id: 'garantias',
        label: 'Garantias',
        path: '/gestao/garantias',
        icon: 'SealCheck',
        description: 'Acompanhamento de prazos de garantia de peças instaladas e serviços prestados.',
      },
      {
        id: 'ferramentas',
        label: 'Ferramentas',
        path: '/gestao/ferramentas',
        icon: 'Wrench',
        description: 'Inventário de equipamentos, scanners, calibrações e ferramentas especiais.',
      },
      {
        id: 'pecas-danificadas',
        label: 'Peças Danificadas',
        path: '/gestao/pecas-danificadas',
        icon: 'WarningOctagon',
        description: 'Registro de peças com avarias, devoluções a fornecedores e descarte correto.',
      },
    ],
  },
  {
    id: 'suprimentos',
    title: 'Suprimentos & Estoque',
    items: [
      {
        id: 'estoque',
        label: 'Estoque',
        path: '/gestao/estoque',
        icon: 'Package',
        description: 'Controle de itens em almoxarifado, níveis mínimos, localização e códigos de barras.',
      },
      {
        id: 'compras',
        label: 'Compras',
        path: '/gestao/compras',
        icon: 'ShoppingCart',
        description: 'Pedidos de compra, cotação com autopeças, recebimento de mercadorias.',
      },
    ],
  },
  {
    id: 'financeiro',
    title: 'Financeiro & Fiscal',
    items: [
      {
        id: 'despesas',
        label: 'Despesas',
        path: '/gestao/despesas',
        icon: 'Receipt',
        description: 'Contas a pagar, custos operacionais fixos e variáveis, fluxo de caixa.',
      },
      {
        id: 'nota-fiscal',
        label: 'Nota Fiscal',
        path: '/gestao/nota-fiscal',
        icon: 'FileText',
        description: 'Emissão e consulta de NFS-e (serviços) e NF-e (venda de peças e produtos).',
      },
      {
        id: 'relatorios',
        label: 'Relatórios',
        path: '/gestao/relatorios',
        icon: 'ChartLineUp',
        description: 'DRE gerencial, produtividade por mecânico, ticket médio e lucratividade.',
      },
    ],
  },
  {
    id: 'sistema',
    title: 'Administração',
    items: [
      {
        id: 'funcionarios',
        label: 'Funcionários',
        path: '/gestao/funcionarios',
        icon: 'IdentificationBadge',
        description: 'Equipe técnica, mecânicos, atendentes, comissões e horários de trabalho.',
      },
      {
        id: 'configuracoes',
        label: 'Configurações',
        path: '/gestao/configuracoes',
        icon: 'GearSix',
        description: 'Parâmetros do sistema, dados da oficina, tabelas de preços e integrações.',
      },
      {
        id: 'site',
        label: 'Site',
        path: '/',
        icon: 'Globe',
        description: 'Retornar ao site institucional público da Mecânica Gabriel.',
        isExternal: true,
      },
    ],
  },
]
