export const MENU_CATEGORIES = [
  {
    id: 'operacoes',
    title: 'Operações',
    items: [
      {
        id: 'resumo',
        label: 'Resumo',
        path: '/gestao/dashboard',
        icon: 'SquaresFour',
        description: 'Visão geral com indicadores principais, faturamento e atendimentos.',
      },
      {
        id: 'agenda',
        label: 'Agenda',
        path: '/gestao/agenda',
        icon: 'CalendarDots',
        description: 'Controle de agendamentos, boxes de atendimento e prazos de entrega.',
      },
      {
        id: 'ordem-de-servico',
        label: 'Ordem de Serviço',
        path: '/gestao/ordem-de-servico',
        icon: 'ClipboardText',
        description: 'Abertura, acompanhamento e finalização de ordens de serviço e orçamentos.',
      },
      {
        id: 'pdv',
        label: 'PDV',
        path: '/gestao/pdv',
        icon: 'CreditCard',
        description: 'Ponto de venda rápido para peças de balcão e pagamentos imediatos.',
      },
    ],
  },
  {
    id: 'atendimento-patio',
    title: 'Atendimento e Pátio',
    items: [
      {
        id: 'clientes',
        label: 'Clientes',
        path: '/gestao/clientes',
        icon: 'Users',
        description: 'Base de clientes com histórico de serviços, dados de contato e veículos.',
      },
      {
        id: 'veiculos',
        label: 'Veículos',
        path: '/gestao/veiculos',
        icon: 'CarProfile',
        description: 'Cadastro detalhado de veículos, placas, quilometragens e manutenções.',
      },
      {
        id: 'estacionados',
        label: 'Estacionados',
        path: '/gestao/estacionados',
        icon: 'Garage',
        description: 'Veículos vendidos de clientes aguardando novo proprietário com histórico preservado.',
      },
      {
        id: 'leva-e-traz',
        label: 'Leva e Traz',
        path: '/gestao/leva-e-traz',
        icon: 'ArrowsLeftRight',
        description: 'Logística de busca e entrega de veículos, translado de clientes e busca de peças.',
      },
    ],
  },
  {
    id: 'suprimentos',
    title: 'Suprimentos',
    items: [
      {
        id: 'compras',
        label: 'Compras',
        path: '/gestao/compras',
        icon: 'ShoppingCart',
        description: 'Gestão de pedidos de compra de autopeças e insumos com fornecedores.',
      },
      {
        id: 'estoque',
        label: 'Estoque',
        path: '/gestao/estoque',
        icon: 'Package',
        description: 'Almoxarifado, níveis de estoque mínimo, localização e inventário.',
      },
      {
        id: 'servicos',
        label: 'Serviços (Mão de Obra)',
        path: '/gestao/servicos',
        icon: 'Hammer',
        description: 'Catálogo de serviços técnicos, tempo estimado e parâmetros fiscais de NFS-e.',
      },
      {
        id: 'pecas',
        label: 'Peças e Produtos',
        path: '/gestao/pecas',
        icon: 'Cube',
        description: 'Cadastro de peças com código de barras GTIN/EAN, NCM, margens e estoque.',
      },
      {
        id: 'fornecedores',
        label: 'Fornecedores',
        path: '/gestao/fornecedores',
        icon: 'Buildings',
        description: 'Cadastro de fornecedores de autopeças, insumos e parceiros de serviços externos.',
      },
    ],
  },
  {
    id: 'oficina-servicos',
    title: 'Oficina e Serviços',
    items: [
      {
        id: 'manutencao-preventiva',
        label: 'Manutenção Preventiva',
        path: '/gestao/manutencao-preventiva',
        icon: 'ShieldCheck',
        description: 'Planos de revisão por quilometragem e alertas programados aos clientes.',
      },
      {
        id: 'garantias',
        label: 'Garantias',
        path: '/gestao/garantias',
        icon: 'SealCheck',
        description: 'Acompanhamento de prazos de garantia de peças e serviços aplicados.',
      },
      {
        id: 'ferramentas',
        label: 'Ferramentas',
        path: '/gestao/ferramentas',
        icon: 'Wrench',
        description: 'Controle de ferramentas especiais, equipamentos de bancada e scanners.',
      },
      {
        id: 'pecas-danificadas',
        label: 'Peças Danificadas',
        path: '/gestao/pecas-danificadas',
        icon: 'WarningOctagon',
        description: 'Registro de peças substituídas, avarias e descarte ambiental responsável.',
      },
    ],
  },
  {
    id: 'financeiro-fiscal',
    title: 'Financeiro e Fiscal',
    items: [
      {
        id: 'despesas',
        label: 'Despesas',
        path: '/gestao/despesas',
        icon: 'Money',
        description: 'Lançamento e controle de despesas operacionais, fixas e variáveis.',
      },
      {
        id: 'nota-fiscal',
        label: 'Nota Fiscal',
        path: '/gestao/nota-fiscal',
        icon: 'FileText',
        description: 'Emissão e consulta de notas fiscais eletrônicas (NFS-e e NF-e).',
      },
      {
        id: 'relatorios',
        label: 'Relatórios',
        path: '/gestao/relatorios',
        icon: 'ChartLineUp',
        description: 'Relatórios de desempenho financeiro, operacional e técnico.',
      },
    ],
  },
  {
    id: 'administracao',
    title: 'Administração',
    items: [
      {
        id: 'funcionarios',
        label: 'Funcionários',
        path: '/gestao/funcionarios',
        icon: 'IdentificationBadge',
        description: 'Gestão da equipe técnica e administrativa, permissões e horários.',
      },
      {
        id: 'configuracoes',
        label: 'Configurações',
        path: '/gestao/configuracoes',
        icon: 'GearSix',
        description: 'Parâmetros do sistema, dados da empresa e preferências de operação.',
      },
      {
        id: 'site',
        label: 'Site',
        path: '/',
        icon: 'Globe',
        description: 'Acessar o site institucional público da Mecânica Gabriel.',
        isExternal: true,
      },
    ],
  },
]
