export const MOCK_MECANICOS = [
  {
    value: '',
    label: 'Não atribuído (Definir na triagem)',
    nome: 'Não atribuído',
    especialidade: 'Aguardando atribuição de bancada',
  },
  {
    value: 'mec-carlos',
    label: 'Carlos Eduardo',
    nome: 'Carlos Eduardo',
    cargo: 'Chefe de Oficina',
    especialidade: 'Injeção Eletrônica e Motor',
    email: 'carlos.eduardo@mecanicagabriel.com.br',
    boxElevador: 'Box 01 (Elevador Hidráulico)',
    comissaoPerc: 15,
    telefone: '(43) 99876-1122',
  },
  {
    value: 'mec-gabriel',
    label: 'Gabriel Amaral',
    nome: 'Gabriel Amaral',
    cargo: 'Mecânico Especialista',
    especialidade: 'Suspensão, Freios e Geometria 3D',
    email: 'gabriel.amaral@mecanicagabriel.com.br',
    boxElevador: 'Box 02 (Alinhador 3D)',
    comissaoPerc: 12,
    telefone: '(43) 99876-3344',
  },
  {
    value: 'mec-rafael',
    label: 'Rafael Salustiano',
    nome: 'Rafael Salustiano',
    cargo: 'Mecânico Pleno',
    especialidade: 'Transmissão, Câmbio e Embreagem',
    email: 'rafael.salustiano@mecanicagabriel.com.br',
    boxElevador: 'Box 03 (Elevador 4 Toneladas)',
    comissaoPerc: 10,
    telefone: '(43) 99876-5566',
  },
  {
    value: 'mec-rodrigo',
    label: 'Rodrigo Alencar',
    nome: 'Rodrigo Alencar',
    cargo: 'Mecânico Especialista',
    especialidade: 'Suspensão e Freios Pesados',
    email: 'rodrigo.alencar@mecanicagabriel.com.br',
    boxElevador: 'Box 04 (Vala de Inspeção)',
    comissaoPerc: 12,
    telefone: '(43) 99876-7788',
  },
  {
    value: 'mec-danilo',
    label: 'Danilo Silva',
    nome: 'Danilo Silva',
    cargo: 'Eletricista Automotivo',
    especialidade: 'Elétrica, Baterias e Ar Condicionado',
    email: 'danilo.silva@mecanicagabriel.com.br',
    boxElevador: 'Box 05 (Bancada Elétrica)',
    comissaoPerc: 12,
    telefone: '(43) 99876-9900',
  },
  {
    value: 'mec-lucas',
    label: 'Lucas Nogueira',
    nome: 'Lucas Nogueira',
    cargo: 'Assistente Técnico',
    especialidade: 'Manutenção Preventiva e Lubrificantes',
    email: 'lucas.nogueira@mecanicagabriel.com.br',
    boxElevador: 'Box Rápido (Troca de Óleo)',
    comissaoPerc: 8,
    telefone: '(43) 99876-0011',
  },
]
