// Dados de seed (mock) usados para popular o localStorage na primeira carga do sistema.
// Extraído de ordensServicoRepository.js (Story 1.11) sem nenhuma alteração de conteúdo.
export const SEED_ORDENS_ABERTAS = [
  {
    numeroOS: '002908',
    dataEntrada: '19/08/2026',
    horaEntrada: '13:05',
    dataEmissao: '19/08/26',
    horaEmissao: '13:05',
    consultorResponsavel: 'BIANCA',
    mecanicoNome: 'Carlos Eduardo',
    clienteId: 'cli-0',
    cliente: 'EDGAR AMARAL DA SILVEIRA',
    documento: '033.687.739-09',
    telefone: '(43) 98812-6874',
    email: 'edgar.silveira@email.com',
    endereco: 'R TUPINAMBA, 566 - Apucarana - PR',
    cidade: 'APUCARANA',
    uf: 'PR',
    cep: '86812-405',
    placa: 'ASF6I46',
    marca: 'FIAT',
    modelo: 'DOBLO 1.8 CARGO',
    marcaModelo: 'Fiat Doblo 1.8 Cargo',
    ano: '2009/2010',
    cor: 'Branca',
    combustivel: 'FLEX',
    km: '280.812',
    kmAnterior: '279.003',
    relatoCliente: 'Barulho na frente ao passar em desníveis e vazamento de água pelo arrefecimento com aquecimento rápido.',
    laudoTecnico: 'Identificado tubo de arrefecimento ressecado com fissura e anel de vedação desgastado. Necessária substituição imediata com limpeza do arrefecimento.',
    status: 'aguardando_aprovacao',
    prioridade: 'normal',
    previsaoEntregaData: '21/08/2026',
    previsaoEntregaHora: '18:00',
    condicaoPagamentoOS: 'À vista com 5% de desconto no PIX ou até 10x no cartão',
    descontoGeralOS: '0.00',
    pecasOS: [
      { codigo: '10039B', nome: 'ANEL VEDADOR DA ADM', unidade: 'UN', quantidade: 4, precoUnitario: 15.0, desconto: 0, marca: 'SABO' },
      { codigo: '0018969', nome: 'TUBO SUPORTE ARREFECIMENTO', unidade: 'PC', quantidade: 1, precoUnitario: 200.0, desconto: 0, marca: 'VALCLEI' },
      { codigo: '2682', nome: 'ABRACADEIRA 14X22', unidade: 'UN', quantidade: 2, precoUnitario: 10.0, desconto: 0, marca: 'SUPREMA' },
      { codigo: '010804', nome: 'ADITIVO A05 PRONTO USO', unidade: 'LT', quantidade: 1, precoUnitario: 40.0, desconto: 0, marca: 'PARAFLU' },
      { codigo: 'DIVERSAS', nome: 'PEÇAS - PARAFUSO C/ PORCA E ARRUELA', unidade: 'PC', quantidade: 1, precoUnitario: 10.0, desconto: 0, marca: 'PADRAO' },
    ],
    servicosOS: [
      { codigo: '01845', nome: 'TROCA TUBO DE AGUA DO COLETOR DE ADM', unidade: 'MO', quantidade: 1, precoUnitario: 300.0, desconto: 0, tempoHoras: '2.5' },
    ],
    terceirosOS: [
      {
        id: 'terc-1',
        codigo: '0019',
        nome: 'TESTE DE ESTANQUEIDADE E PRESSAO DO RADIADOR',
        parceiroNome: 'Radiadores Apucarana',
        quantidade: 1,
        custo: 80.0,
        valorVenda: 120.0,
        precoUnitario: 120.0,
        desconto: 0,
      },
    ],
    totalPecas: 330.0,
    totalServicos: 300.0,
    totalTerceiros: 120.0,
    descontoTotal: 0.0,
    valorTotal: 750.0,
  },
  {
    numeroOS: '002909',
    dataEntrada: '19/08/2026',
    horaEntrada: '08:30',
    dataEmissao: '19/08/26',
    horaEmissao: '08:30',
    consultorResponsavel: 'BIANCA',
    mecanicoNome: 'Gabriel Amaral',
    clienteId: 'cli-1',
    cliente: 'CARLOS EDUARDO SILVEIRA',
    documento: '284.910.482-15',
    telefone: '(43) 99123-4567',
    email: 'carlos.silveira@email.com',
    endereco: 'Rua das Palmeiras, 342 - Londrina - PR',
    cidade: 'LONDRINA',
    uf: 'PR',
    cep: '86010-000',
    placa: 'BRA2E19',
    marca: 'CHEVROLET',
    modelo: 'ONIX 1.0 TURBO',
    marcaModelo: 'Chevrolet Onix 1.0 Turbo',
    ano: '2022/2023',
    cor: 'Preto Ouro Negro',
    combustivel: 'FLEX',
    km: '38.450',
    relatoCliente: 'Luz da injeção acesa intermitente, falha de aceleração em subidas e consumo elevado de combustível.',
    laudoTecnico: 'Diagnóstico com scanner acusando falha no bico injetor do cilindro 2 e descalibração na sonda lambda.',
    status: 'em_diagnostico',
    prioridade: 'normal',
    previsaoEntregaData: '20/08/2026',
    previsaoEntregaHora: '17:00',
    condicaoPagamentoOS: 'Em até 6x no cartão de crédito',
    descontoGeralOS: '0.00',
    pecasOS: [
      { codigo: '001290', nome: 'VELA DE IGNICAO IRIDIUM', unidade: 'JG', quantidade: 1, precoUnitario: 180.0, desconto: 0, marca: 'NGK' },
    ],
    servicosOS: [
      { codigo: '00921', nome: 'DIAGNOSTICO COMPUTADORIZADO E TESTE DE BICOS', unidade: 'MO', quantidade: 1, precoUnitario: 220.0, desconto: 0, tempoHoras: '1.5' },
    ],
    terceirosOS: [],
    totalPecas: 180.0,
    totalServicos: 220.0,
    totalTerceiros: 0.0,
    descontoTotal: 0.0,
    valorTotal: 400.0,
  },
  {
    numeroOS: '002910',
    dataEntrada: '18/08/2026',
    horaEntrada: '14:15',
    dataEmissao: '18/08/26',
    horaEmissao: '14:15',
    consultorResponsavel: 'BIANCA',
    mecanicoNome: 'Rafael Salustiano',
    clienteId: 'cli-2',
    cliente: 'MARIANA DUARTE SOUZA',
    documento: '049.321.890-44',
    telefone: '(43) 98845-1290',
    email: 'mariana.souza@gmail.com',
    endereco: 'Av. Ayrton Senna, 1150 - Gleba Palhano, Londrina - PR',
    cidade: 'LONDRINA',
    uf: 'PR',
    cep: '86050-460',
    placa: 'BDX9F12',
    marca: 'HYUNDAI',
    modelo: 'HB20 1.0 SENSE',
    marcaModelo: 'Hyundai HB20 1.0 Sense',
    ano: '2020/2021',
    cor: 'Branco Polar',
    combustivel: 'FLEX',
    km: '64.800',
    relatoCliente: 'Barulho metálico áspero ao frear e pedal vibrando nas frenagens médias em rodovia.',
    laudoTecnico: 'Discos de freio dianteiros com empenamento e pastilhas no final da vida útil. Bieletas com folga na bucha.',
    status: 'aguardando_pecas',
    prioridade: 'urgente',
    previsaoEntregaData: '20/08/2026',
    previsaoEntregaHora: '16:30',
    condicaoPagamentoOS: 'PIX à vista com 5% de desconto',
    descontoGeralOS: '0.00',
    pecasOS: [
      { codigo: '011290', nome: 'PASTILHA DE FREIO CERAMICA', unidade: 'JG', quantidade: 1, precoUnitario: 195.0, desconto: 0, marca: 'FRAS-LE' },
      { codigo: '011291', nome: 'DISCO DE FREIO VENTILADO', unidade: 'PR', quantidade: 1, precoUnitario: 380.0, desconto: 0, marca: 'FREMAX' },
      { codigo: '011292', nome: 'FLUIDO DE FREIO DOT 4 500ML', unidade: 'FR', quantidade: 2, precoUnitario: 35.0, desconto: 0, marca: 'VARGAS' },
      { codigo: '015290', nome: 'BIELETA BARRA ESTABILIZADORA', unidade: 'PR', quantidade: 1, precoUnitario: 95.0, desconto: 0, marca: 'COFAP' },
    ],
    servicosOS: [
      { codigo: '00341', nome: 'SUBSTITUICAO DISCOS E PASTILHAS DE FREIO', unidade: 'MO', quantidade: 1, precoUnitario: 220.0, desconto: 0, tempoHoras: '1.8' },
      { codigo: '00342', nome: 'SANGRIA E TROCA DE FLUIDO DOT4', unidade: 'MO', quantidade: 1, precoUnitario: 130.0, desconto: 0, tempoHoras: '1.0' },
    ],
    terceirosOS: [],
    totalPecas: 735.0,
    totalServicos: 350.0,
    totalTerceiros: 0.0,
    descontoTotal: 0.0,
    valorTotal: 1085.0,
  },
  {
    numeroOS: '002911',
    dataEntrada: '18/08/2026',
    horaEntrada: '09:00',
    dataEmissao: '18/08/26',
    horaEmissao: '09:00',
    consultorResponsavel: 'BIANCA',
    mecanicoNome: 'Carlos Eduardo',
    clienteId: 'cli-3',
    cliente: 'TRANSPORTADORA RÁPIDO NORTE LTDA',
    documento: '14.892.401/0001-92',
    telefone: '(43) 3344-9000',
    email: 'frotas@rapidolondrina.com.br',
    endereco: 'Rodovia Celso Garcia Cid, KM 378 - Londrina - PR',
    cidade: 'LONDRINA',
    uf: 'PR',
    cep: '86040-000',
    placa: 'RAW3H55',
    marca: 'FIAT',
    modelo: 'FIORINO 1.4 HARD WORKING',
    marcaModelo: 'Fiat Fiorino 1.4 Hard Working',
    ano: '2021/2022',
    cor: 'Branco Banchisa',
    combustivel: 'FLEX',
    km: '89.300',
    relatoCliente: 'Revisão periódica programada de 90.000 KM para veículos de entrega rápida da frota.',
    laudoTecnico: 'Troca de kit da correia dentada, tensor, bomba de água e troca de óleos e filtros. Veículo apto após serviços.',
    status: 'aprovado_execucao',
    prioridade: 'urgente',
    previsaoEntregaData: '19/08/2026',
    previsaoEntregaHora: '17:30',
    condicaoPagamentoOS: 'Faturamento em 28 dias boleto para PJ',
    descontoGeralOS: '50.00',
    pecasOS: [
      { codigo: '009182', nome: 'CORREIA DENTADA SINCRONIZADORA', unidade: 'UN', quantidade: 1, precoUnitario: 120.0, desconto: 0, marca: 'GATES' },
      { codigo: '009183', nome: 'TENSOR DA CORREIA DENTADA', unidade: 'UN', quantidade: 1, precoUnitario: 145.0, desconto: 0, marca: 'INA' },
      { codigo: '008271', nome: 'BOMBA DAGUA MOTOR FIRE', unidade: 'UN', quantidade: 1, precoUnitario: 240.0, desconto: 0, marca: 'URBA' },
      { codigo: '006722', nome: 'OLEO SINTETICO 5W30 SP', unidade: 'LT', quantidade: 4, precoUnitario: 52.0, desconto: 0, marca: 'PETRONAS' },
      { codigo: '006721', nome: 'FILTRO DE OLEO MOTOR', unidade: 'UN', quantidade: 1, precoUnitario: 38.0, desconto: 0, marca: 'FRAM' },
      { codigo: '006723', nome: 'FILTRO DE AR MOTOR', unidade: 'UN', quantidade: 1, precoUnitario: 45.0, desconto: 0, marca: 'TECFIL' },
    ],
    servicosOS: [
      { codigo: '00501', nome: 'TROCA KIT CORREIA DENTADA E BOMBA DAGUA', unidade: 'MO', quantidade: 1, precoUnitario: 380.0, desconto: 0, tempoHoras: '3.0' },
      { codigo: '00502', nome: 'REVISAO GERAL DE FLUIDOS E FILTROS', unidade: 'MO', quantidade: 1, precoUnitario: 140.0, desconto: 0, tempoHoras: '1.2' },
    ],
    terceirosOS: [],
    totalPecas: 796.0,
    totalServicos: 520.0,
    totalTerceiros: 0.0,
    descontoTotal: 50.0,
    valorTotal: 1266.0,
  },
  {
    numeroOS: '002912',
    dataEntrada: '17/08/2026',
    horaEntrada: '10:20',
    dataEmissao: '17/08/26',
    horaEmissao: '10:20',
    consultorResponsavel: 'BIANCA',
    mecanicoNome: 'Gabriel Amaral',
    clienteId: 'cli-4',
    cliente: 'LUCIANA MENDONÇA',
    documento: '582.109.843-20',
    telefone: '(43) 99654-2211',
    email: 'luciana.mendonca@gmail.com',
    endereco: 'Rua Piauí, 890 - Centro, Londrina - PR',
    cidade: 'LONDRINA',
    uf: 'PR',
    cep: '86010-420',
    placa: 'RHJ4A88',
    marca: 'TOYOTA',
    modelo: 'COROLLA CROSS XRE 2.0',
    marcaModelo: 'Toyota Corolla Cross XRE 2.0',
    ano: '2021/2022',
    cor: 'Prata Lua Nova',
    combustivel: 'FLEX',
    km: '52.120',
    relatoCliente: 'Odor desagradável ao ligar o ar condicionado e leve puxada da direção para a direita.',
    laudoTecnico: 'Higienização por ozônio do sistema de climatização, troca do filtro de carvão ativado e alinhamento/balanceamento computadorizado concluídos.',
    status: 'pronto_retirada',
    prioridade: 'normal',
    previsaoEntregaData: '19/08/2026',
    previsaoEntregaHora: '11:30',
    condicaoPagamentoOS: 'Cartão de débito ou PIX',
    descontoGeralOS: '0.00',
    pecasOS: [
      { codigo: '006725', nome: 'FILTRO AR CONDICIONADO CABINE CARVAO ATIVADO', unidade: 'UN', quantidade: 1, precoUnitario: 80.0, desconto: 0, marca: 'WEGA' },
      { codigo: '008910', nome: 'HIGIENIZADOR DE AR CONDICIONADO GRANADA', unidade: 'UN', quantidade: 1, precoUnitario: 40.0, desconto: 0, marca: 'WURTH' },
    ],
    servicosOS: [
      { codigo: '00710', nome: 'HIGIENIZACAO POR OZONIO E TROCA FILTRO CABINE', unidade: 'MO', quantidade: 1, precoUnitario: 120.0, desconto: 0, tempoHoras: '0.8' },
      { codigo: '00711', nome: 'ALINHAMENTO 3D E BALANCEAMENTO DE 4 RODAS', unidade: 'MO', quantidade: 1, precoUnitario: 140.0, desconto: 0, tempoHoras: '1.0' },
    ],
    terceirosOS: [],
    totalPecas: 120.0,
    totalServicos: 260.0,
    totalTerceiros: 0.0,
    descontoTotal: 0.0,
    valorTotal: 380.0,
  },
  {
    numeroOS: '002913',
    dataEntrada: '19/08/2026',
    horaEntrada: '09:15',
    dataEmissao: '19/08/26',
    horaEmissao: '09:15',
    consultorResponsavel: 'BIANCA',
    mecanicoNome: 'Carlos Eduardo',
    clienteId: 'cli-5',
    cliente: 'ROBERTO FAGUNDES NETO',
    documento: '719.452.190-33',
    telefone: '(43) 99188-3344',
    email: 'roberto.fagundes@uol.com.br',
    endereco: 'Rua Sergipe, 1400 - Londrina - PR',
    cidade: 'LONDRINA',
    uf: 'PR',
    cep: '86010-540',
    placa: 'RBD3A45',
    marca: 'VOLKSWAGEN',
    modelo: 'T-CROSS 1.0 TSI',
    marcaModelo: 'Volkswagen T-Cross 1.0 TSI',
    ano: '2021/2021',
    cor: 'Cinza Platinum',
    combustivel: 'FLEX',
    km: '48.900',
    relatoCliente: 'Pedal de embreagem pesado e com ruído metálico ao pisar. Dificuldade de engate da 1ª marcha e ré.',
    laudoTecnico: 'Rolamento de desengate com folga axial excessiva e platô com marcas de superaquecimento. Recomendada troca do kit de embreagem e fluido hidráulico.',
    status: 'aguardando_aprovacao',
    prioridade: 'normal',
    previsaoEntregaData: '22/08/2026',
    previsaoEntregaHora: '12:00',
    condicaoPagamentoOS: 'Em até 10x sem juros no cartão',
    descontoGeralOS: '0.00',
    pecasOS: [
      { codigo: '018901', nome: 'KIT EMBREAGEM PLATO DISCO ROLAMENTO', unidade: 'JG', quantidade: 1, precoUnitario: 1250.0, desconto: 0, marca: 'LUK' },
      { codigo: '011292', nome: 'FLUIDO HIDRAULICO DOT 4', unidade: 'FR', quantidade: 1, precoUnitario: 35.0, desconto: 0, marca: 'VARGAS' },
    ],
    servicosOS: [
      { codigo: '00892', nome: 'SUBSTITUICAO KIT DE EMBREAGEM E SANGRIA', unidade: 'MO', quantidade: 1, precoUnitario: 650.0, desconto: 0, tempoHoras: '4.5' },
    ],
    terceirosOS: [],
    totalPecas: 1285.0,
    totalServicos: 650.0,
    totalTerceiros: 0.0,
    descontoTotal: 0.0,
    valorTotal: 1935.0,
  },
]
