// Dados de seed (mock) usados para popular o localStorage na primeira carga do sistema.
// Extraído de ordensServicoRepository.js (Story 1.11) sem nenhuma alteração de conteúdo.
export const SEED_ORDENS_FINALIZADAS = [
  {
    numeroOS: '002895',
    dataEntrada: '08/08/2026',
    horaEntrada: '09:00',
    dataEmissao: '08/08/26',
    horaEmissao: '09:00',
    dataFinalizacao: '10/08/2026',
    horaFinalizacao: '16:45',
    consultorResponsavel: 'BIANCA',
    mecanicoNome: 'Carlos Eduardo',
    clienteId: 'cli-0',
    cliente: 'EDGAR AMARAL DA SILVEIRA',
    documento: '033.687.739-09',
    telefone: '(43) 98812-6874',
    email: 'edgar.silveira@email.com',
    endereco: 'R TUPINAMBA, 566 - Apucarana - PR',
    cidade: 'APUCARANA',
    uf: 'PR',
    cep: '86812-405',
    placa: 'ASF6I46',
    marca: 'FIAT',
    modelo: 'DOBLO 1.8 CARGO',
    marcaModelo: 'Fiat Doblo 1.8 Cargo',
    ano: '2009/2010',
    cor: 'Branca',
    combustivel: 'FLEX',
    km: '279.003',
    relatoCliente: 'Revisão básica periódica para viagem curta de trabalho e troca preventiva de lubrificantes.',
    laudoTecnico: 'Troca de óleo do motor 5W30, filtro de óleo, filtro de combustível e filtro de ar do motor. Inspeção geral de suspensão OK.',
    status: 'finalizada',
    prioridade: 'normal',
    garantiaAte: '10/11/2026',
    formaPagamento: 'PIX à vista',
    notaFiscal: 'NFS-e #002814',
    condicaoPagamentoOS: 'Pago via PIX com 5% de desconto',
    descontoGeralOS: '0.00',
    pecasOS: [
      { codigo: '006722', nome: 'OLEO SINTETICO 5W30 SP', unidade: 'LT', quantidade: 4, precoUnitario: 52.0, desconto: 0, marca: 'PETRONAS' },
      { codigo: '006721', nome: 'FILTRO DE OLEO MOTOR', unidade: 'UN', quantidade: 1, precoUnitario: 38.0, desconto: 0, marca: 'FRAM' },
      { codigo: '006723', nome: 'FILTRO DE AR MOTOR', unidade: 'UN', quantidade: 1, precoUnitario: 45.0, desconto: 0, marca: 'TECFIL' },
      { codigo: '006724', nome: 'FILTRO DE COMBUSTIVEL', unidade: 'UN', quantidade: 1, precoUnitario: 32.0, desconto: 0, marca: 'MAHLE' },
    ],
    servicosOS: [
      { codigo: '00101', nome: 'TROCA DE OLEO E FILTROS COM REVISAO BASICA', unidade: 'MO', quantidade: 1, precoUnitario: 120.0, desconto: 0, tempoHoras: '1.0' },
    ],
    terceirosOS: [],
    totalPecas: 323.0,
    totalServicos: 120.0,
    totalTerceiros: 0.0,
    descontoTotal: 0.0,
    valorTotal: 443.0,
  },
  {
    numeroOS: '002896',
    dataEntrada: '11/08/2026',
    horaEntrada: '11:10',
    dataEmissao: '11/08/26',
    horaEmissao: '11:10',
    dataFinalizacao: '12/08/2026',
    horaFinalizacao: '17:30',
    consultorResponsavel: 'BIANCA',
    mecanicoNome: 'Rafael Salustiano',
    clienteId: 'cli-2',
    cliente: 'MARIANA DUARTE SOUZA',
    documento: '049.321.890-44',
    telefone: '(43) 98845-1290',
    email: 'mariana.souza@gmail.com',
    endereco: 'Av. Ayrton Senna, 1150 - Gleba Palhano, Londrina - PR',
    cidade: 'LONDRINA',
    uf: 'PR',
    cep: '86050-460',
    placa: 'BDX9F12',
    marca: 'HYUNDAI',
    modelo: 'HB20 1.0 SENSE',
    marcaModelo: 'Hyundai HB20 1.0 Sense',
    ano: '2020/2021',
    cor: 'Branco Polar',
    combustivel: 'FLEX',
    km: '61.200',
    relatoCliente: 'Barulho de batida seca na dianteira direita ao passar em lombadas e asfalto irregular.',
    laudoTecnico: 'Amortecedor dianteiro direito vazando óleo e kit batente estourado. Substituído par de amortecedores e batentes.',
    status: 'finalizada',
    prioridade: 'normal',
    garantiaAte: '12/11/2026',
    formaPagamento: 'Cartão de Crédito 3x',
    notaFiscal: 'NFS-e #002819',
    condicaoPagamentoOS: 'Em 3x no cartão sem juros',
    descontoGeralOS: '0.00',
    pecasOS: [
      { codigo: '014290', nome: 'AMORTECEDOR DIANTEIRO PRESSURIZADO', unidade: 'PR', quantidade: 1, precoUnitario: 680.0, desconto: 0, marca: 'COFAP' },
      { codigo: '014291', nome: 'KIT BATENTE E COIFA AMORTECEDOR', unidade: 'JG', quantidade: 1, precoUnitario: 130.0, desconto: 0, marca: 'SAMPEL' },
    ],
    servicosOS: [
      { codigo: '00205', nome: 'SUBSTITUICAO AMORTECEDORES DIANTEIROS E ALINHAMENTO', unidade: 'MO', quantidade: 1, precoUnitario: 240.0, desconto: 0, tempoHoras: '2.0' },
    ],
    terceirosOS: [],
    totalPecas: 810.0,
    totalServicos: 240.0,
    totalTerceiros: 0.0,
    descontoTotal: 0.0,
    valorTotal: 1050.0,
  },
  {
    numeroOS: '002897',
    dataEntrada: '14/08/2026',
    horaEntrada: '08:00',
    dataEmissao: '14/08/26',
    horaEmissao: '08:00',
    dataFinalizacao: '15/08/2026',
    horaFinalizacao: '18:15',
    consultorResponsavel: 'BIANCA',
    mecanicoNome: 'Carlos Eduardo',
    clienteId: 'cli-3',
    cliente: 'TRANSPORTADORA RÁPIDO NORTE LTDA',
    documento: '14.892.401/0001-92',
    telefone: '(43) 3344-9000',
    email: 'frotas@rapidolondrina.com.br',
    endereco: 'Rodovia Celso Garcia Cid, KM 378 - Londrina - PR',
    cidade: 'LONDRINA',
    uf: 'PR',
    cep: '86040-000',
    placa: 'RAW3H55',
    marca: 'FIAT',
    modelo: 'FIORINO 1.4 HARD WORKING',
    marcaModelo: 'Fiat Fiorino 1.4 Hard Working',
    ano: '2021/2022',
    cor: 'Branco Banchisa',
    combustivel: 'FLEX',
    km: '79.800',
    relatoCliente: 'Revisão preventiva periódica de 80.000 KM para veículos de entrega da frota.',
    laudoTecnico: 'Troca de velas de ignição, cabos de vela, limpeza de bicos e troca de fluidos de freio.',
    status: 'finalizada',
    prioridade: 'normal',
    garantiaAte: '15/11/2026',
    formaPagamento: 'Faturamento Boleto 28D',
    notaFiscal: 'NFS-e #002824',
    condicaoPagamentoOS: 'Faturado para PJ em 28 dias',
    descontoGeralOS: '40.00',
    pecasOS: [
      { codigo: '001290', nome: 'VELA DE IGNICAO GREEN PLUG', unidade: 'JG', quantidade: 1, precoUnitario: 110.0, desconto: 0, marca: 'NGK' },
      { codigo: '001291', nome: 'CABOS DE VELA SILICONE', unidade: 'JG', quantidade: 1, precoUnitario: 160.0, desconto: 0, marca: 'NGK' },
      { codigo: '011292', nome: 'FLUIDO DE FREIO DOT 4 500ML', unidade: 'FR', quantidade: 2, precoUnitario: 35.0, desconto: 0, marca: 'VARGAS' },
    ],
    servicosOS: [
      { codigo: '00311', nome: 'REVISAO ELETRICA DE IGNICAO E SANGRIA DE FREIOS', unidade: 'MO', quantidade: 1, precoUnitario: 260.0, desconto: 0, tempoHoras: '2.2' },
    ],
    terceirosOS: [],
    totalPecas: 340.0,
    totalServicos: 260.0,
    totalTerceiros: 0.0,
    descontoTotal: 40.0,
    valorTotal: 560.0,
  },
  {
    numeroOS: '002898',
    dataEntrada: '15/08/2026',
    horaEntrada: '10:40',
    dataEmissao: '15/08/26',
    horaEmissao: '10:40',
    dataFinalizacao: '16/08/2026',
    horaFinalizacao: '15:20',
    consultorResponsavel: 'BIANCA',
    mecanicoNome: 'Gabriel Amaral',
    clienteId: 'cli-1',
    cliente: 'CARLOS EDUARDO SILVEIRA',
    documento: '284.910.482-15',
    telefone: '(43) 99123-4567',
    email: 'carlos.silveira@email.com',
    endereco: 'Rua das Palmeiras, 342 - Londrina - PR',
    cidade: 'LONDRINA',
    uf: 'PR',
    cep: '86010-000',
    placa: 'BRA2E19',
    marca: 'CHEVROLET',
    modelo: 'ONIX 1.0 TURBO',
    marcaModelo: 'Chevrolet Onix 1.0 Turbo',
    ano: '2022/2023',
    cor: 'Preto Ouro Negro',
    combustivel: 'FLEX',
    km: '34.100',
    relatoCliente: 'Chiado no freio ao parar nos semáforos da cidade.',
    laudoTecnico: 'Pastilhas de freio dianteiras gastas atingindo marcador acústico. Discos em ótimo estado. Pastilhas substituídas.',
    status: 'finalizada',
    prioridade: 'normal',
    garantiaAte: '16/11/2026',
    formaPagamento: 'Cartão de Débito',
    notaFiscal: 'NFS-e #002830',
    condicaoPagamentoOS: 'Cartão de Débito',
    descontoGeralOS: '0.00',
    pecasOS: [
      { codigo: '011290', nome: 'PASTILHA DE FREIO DIANTEIRA CERAMICA', unidade: 'JG', quantidade: 1, precoUnitario: 195.0, desconto: 0, marca: 'FRAS-LE' },
    ],
    servicosOS: [
      { codigo: '00140', nome: 'SUBSTITUICAO DE PASTILHAS DE FREIO E TESTE DE RODAGEM', unidade: 'MO', quantidade: 1, precoUnitario: 130.0, desconto: 0, tempoHoras: '1.0' },
    ],
    terceirosOS: [],
    totalPecas: 195.0,
    totalServicos: 130.0,
    totalTerceiros: 0.0,
    descontoTotal: 0.0,
    valorTotal: 325.0,
  },
]
